add description and examples for `exclusiveMinimum` keyword
Intelligence-AI/learnjsonschema.com pull request #115
Opened 2024-02-18 13:36 UTC by AgniveshChaubey

This PR addresses #93

2024-02-19 13:09 UTC, jviotti requested changes

2024-02-19 13:09 UTC, jviotti commented on content/2020-12/validation/exclusiveMinimum.markdown
> +* Applies only to number data types (integers and floats).
JSON doesn't define "floats" per se (which are specific representation of real numbers) but "real numbers". Can we say real numbers instead in these two PRs?

2024-02-19 13:09 UTC, jviotti commented on content/2020-12/validation/exclusiveMinimum.markdown
> +## Examples
Can we tweak one of the examples to show off setting `exclusiveMinimum` to a real number and how that validates against integers & reals?

2024-02-19 13:09 UTC, jviotti commented on content/2020-12/validation/exclusiveMinimum.markdown
> +* _**Note:** Here, the `exclusiveMinimum` takes precedence, even though `minimum` is 5. Only numbers greater than 10 are valid._
Great example!

2024-02-20 07:17 UTC, AgniveshChaubey commented on content/2020-12/validation/exclusiveMinimum.markdown
> +## Examples
Sure! Let me tweak the second one.

2024-02-20 12:29 UTC, jviotti approved these changes

2024-02-20 13:15 UTC, merged