Keyword `format` (annotation)
Intelligence-AI/learnjsonschema.com pull request #138
Opened 2024-03-31 18:23 UTC by AgniveshChaubey

This PR addresses #78.

2024-04-01 15:44 UTC, jviotti commented on content/2020-12/format-annotation/format.markdown
> +The `format` keyword in JSON Schema's Format Annotation vocabulary serves to provide basic semantic identification of certain types of string values. Compared to older JSON Schema drafts, the `format
```suggestion
The `format` keyword in JSON Schema's Format Annotation vocabulary serves to provide basic semantic identification of certain types of string values. Compared to older JSON Schema versions, the `format` keyword in the official 2020-12 dialect is purely an annotation meant to be informative and to carry semantics rather than to perform any validation.
```

2024-04-01 15:46 UTC, jviotti commented on content/2020-12/format-annotation/format.markdown
> +When using `format` from Format Annotation, it's expected that you provide your validation rules alongside the `format`. The implementation may choose to treat `format` as an assertion and attempt to
> it's expected that you provide your validation rules alongside the `format`

Let's say its recommended.

> The implementation may choose to treat `format` as an assertion and attempt to validate the value's conformance to the specified semantics. However, this behavior must be explicitly enabled and is typically disabled by default. Implementations should document their level of support for such validation.

This is not correct. An implementation that allows you optionally treat them as validation is non compliant. If you are using Format Annotation, the implementation MUST NOT treat that as a validation constraint under any circumstance. If you want assertions, you should use Format Assertion

2024-04-01 15:46 UTC, jviotti commented on content/2020-12/format-annotation/format.markdown
> +* Implementations may choose to enable format as an assertion, meaning that validation fails if the value doesn't conform to the specified format semantics. However, this is not mandatory and must be
Again, this would be non-compliant

2024-04-01 15:47 UTC, jviotti commented on content/2020-12/format-annotation/format.markdown
> +* While users can define and use their own custom `formats` (e.g., "format": "foobar"), it's recommended to refrain from overloading the format keyword for future compatibility reasons. Instead, defi
This is a good point! You can even explain further saying that if you define your own `foobar` and JSON Schema later decides to define `foobar`, you will be in trouble

2024-04-01 18:01 UTC, AgniveshChaubey commented on content/2020-12/format-annotation/format.markdown
> +When using `format` from Format Annotation, it's expected that you provide your validation rules alongside the `format`. The implementation may choose to treat `format` as an assertion and attempt to
> This is not correct. An implementation that allows you optionally treat them as validation is non compliant. If you are using Format Annotation, the implementation MUST NOT treat that as a validation constraint under any circumstance. If you want assertions, you should use Format Assertion

But, the [spec](https://json-schema.org/draft/2020-12/json-schema-validation#section-7.2.1) says implementations can optionally choose to do so.

> Implementations MAY still treat "format" as an assertion in addition to an annotation and attempt to validate the value's conformance to the specified semantics.

2024-04-01 21:24 UTC, jviotti commented on content/2020-12/format-annotation/format.markdown
> +When using `format` from Format Annotation, it's expected that you provide your validation rules alongside the `format`. The implementation may choose to treat `format` as an assertion and attempt to
Ah, interesting. I didn't realize that. Fine then, but can you link this part to the spec?

2024-04-03 15:15 UTC, jviotti requested changes

2024-04-03 15:15 UTC, jviotti commented on content/2020-12/format-annotation/format.markdown
> +## Examples
I just checked given the other PRs and `format` is collected as an annotation. Can you add annotation examples here too?

2024-04-03 15:58 UTC, AgniveshChaubey commented
Annotation added!

2024-04-04 22:36 UTC, jviotti approved these changes

2024-04-05 11:26 UTC, merged