Keyword `format` (assertion)
Intelligence-AI/learnjsonschema.com pull request #139
Opened 2024-03-31 18:24 UTC by AgniveshChaubey

This PR addresses #79

2024-04-01 15:52 UTC, jviotti commented on content/2020-12/format-assertion/format.markdown
> +  "$vocabulary": {
This is not correct. `$vocabulary` will not apply to instances of the schema directly. You need to define a separate schema with `$vocabulary` and use that in `$schema` of another schema to make it work

2024-04-01 18:17 UTC, AgniveshChaubey commented on content/2020-12/format-assertion/format.markdown
> +  "$vocabulary": {
I have negligible experience dealing with custom vocabularies. I tried this example with JSON-everything and it surprisingly it worked! That's why I added it here 😅.

You mean something like this?

meta-schema:
```json
{
  "$schema": "https://example.com/custom-meta-schema",
  "$id": "https://example.com/custom-meta-schema",
  "$vocabulary": {
    "https://json-schema.org/draft/2020-12/vocab/format-assertion": true
  },
  "allOf": [
    { "$ref": "https://json-schema.org/draft/2019-06/schema#" }
  ]
}
```

schema:
```json
{
  "$schema": "https://example.com/custom-meta-schema",
  "$id": "https://example.com/schema",
  "format": "email"
}
```

2024-04-01 21:27 UTC, jviotti commented on content/2020-12/format-assertion/format.markdown
> +  "$vocabulary": {
Correct, but in every meta-schema you must always import the "core" vocabulary (the lack of it is considered an error). Plus instead of validating against the entirety of https://json-schema.org/draft/2020-12/schema in `allOf`, you can validate against the specific vocabulary meta-schemas: https://json-schema.org/draft/2020-12/meta/core and https://json-schema.org/draft/2020-12/meta/format-assertion.

Interesting that the other one work on JSON Everything. I believe the lack of consistency between implementations is a key problem in JSON Schema. Hard to know what's implementation-dependent and what's not for the average user

2024-04-02 12:26 UTC, AgniveshChaubey commented
Updated the example by creating a separate `meta-schema` and referencing it from another schema. Kindly check it and let me know if it is correct.

2024-04-02 12:36 UTC, AgniveshChaubey commented on content/2020-12/format-assertion/format.markdown
> +  "$vocabulary": {
Aren't there any standard set of rules that implementers must follow when writing their implementation to maintain consistency?

2024-04-03 15:16 UTC, jviotti commented on content/2020-12/format-assertion/format.markdown
> +  "$vocabulary": {
They are, but they are often a bit loose IMO. Also, vocabularies are an experimental feature not fully fledged out (which carries its own problem!)

2024-04-03 15:18 UTC, jviotti requested changes

2024-04-03 15:18 UTC, jviotti commented on content/2020-12/format-assertion/format.markdown
> +## Examples
Example looks good, but as I commented in the other `format` PR, `format` emits an annotation. Can we add that to the examples?

2024-04-03 16:00 UTC, AgniveshChaubey commented
Annotation added!

2024-04-04 22:35 UTC, jviotti approved these changes

2024-04-05 11:25 UTC, merged