Adding dropdown,
Intelligence-AI/learnjsonschema.com pull request #165
Opened 2024-05-03 20:49 UTC by Era-cell

Features: dropdown on hover
redirect to http://base.com/{selected_dialect}

2024-05-06 13:29 UTC, jviotti commented on layouts/partials/sidebar.html
> +      <button class="dropdown-button fw-bold ps-0" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-expanded="false">
Can we style this button a more prominently and differently than the vocabulary accordions? Right now I feel like its not clear that its even clickable

2024-05-06 13:30 UTC, jviotti commented on layouts/partials/sidebar.html
> +      <button class="dropdown-button fw-bold ps-0" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-expanded="false">
I also noticed that this dropdown opens automatically when you however, while the Bootstrap one gets opened only when you click it? Can we get Bootstrap click behavior instead?

2024-05-06 13:31 UTC, jviotti commented on layouts/partials/sidebar.html
> +<style>
In general, the point of Bootstrap is that they have a lot of pre-made components that are even customizable using SCSS variables so that you can avoid writing actual CSS in the vast majority of cases

2024-05-06 19:12 UTC, Era-cell commented on layouts/partials/sidebar.html
> +      <button class="dropdown-button fw-bold ps-0" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-expanded="false">
Wait.. can I get help on this: for the javascript to 

Uploading Recording 2024-05-07 004034.mp4…

work I am assigning objects as you have done in the tooltip like this,
![Screenshot 2024-05-07 003740](https://github.com/Intelligence-AI/learnjsonschema.com/assets/77973415/24449758-0201-4e74-9e59-7416e1f00191)
But seems that javascript from bootstrap isn't working properly or it behaving this way by the affect of hugo components,

2024-05-06 23:28 UTC, jviotti commented
@Era-cell There are a few things missing, some of which were non-obvious:

- You need to enable the dropdown SCSS partials from Bootstrap in `assets/main.scss`
- The HTML for the dropdown was incorrect. For example, the button should have had the class `dropdown-toggle` instead of `dropdown-button` and the anchors needed the class `dropdown-item` (which the documentation shows)
- You had to tweak `vendor/bootstrap.mask` and re-run [`vendorpull`](https://github.com/sourcemeta/vendorpull) to actually pull the Bootstrap dropdown JavaScript plugin
- Finally, instantiate the plugin in `assets/main.js`
- Plus you can get rid of the inline styles you had there

Let me do at least some of those changes for you and push a commit here

2024-05-06 23:34 UTC, jviotti commented
Done. Give it a shot yourself. Though now that I play with it, I wonder if putting the dropdown on the sidebar is the right place... maybe same dropdown but on either the breadcrumb or the navigation bar would feel better... Let me play with it a bit

2024-05-06 23:59 UTC, jviotti commented
I went back and forth on it a lot, but I think I quite like it in the breadcrumb, and instead of saying "2020-12" we say something like "Other dialects" or "Explore other dialects":

![Screenshot 2024-05-06 195805](https://github.com/Intelligence-AI/learnjsonschema.com/assets/2192773/648bd545-9f8c-422f-afe6-41327d39acfc)

What do you think? I did with a `btn btn-sm btn-outline-primary`

2024-05-07 01:58 UTC, Era-cell commented
Oh!!  now I get it. I was masked in bootstrap.mask, 😵‍💫 I wasted a lot of time

2024-05-07 17:41 UTC, Era-cell commented
> I went back and forth on it a lot, but I think I quite like it in the breadcrumb, and instead of saying "2020-12" we say something like "Other dialects" or "Explore other dialects":
> 
> ![Screenshot 2024-05-06 195805](https://private-user-images.githubusercontent.com/2192773/328346511-648bd545-9f8c-422f-afe6-41327d39acfc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxMDIyMzUsIm5iZiI6MTcxNTEwMTkzNSwicGF0aCI6Ii8yMTkyNzczLzMyODM0NjUxMS02NDhiZDU0NS05ZjhjLTQyMmYtYWZlNi00MTMyN2QzOWFjZmMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDdUMTcxMjE1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OWE3NWI5N2QzYjZlNjA2Y2MxYjFlZGRlZjI4YTRmMDFlZTZmZTNhMWE0OWUzNGQwZmU5NTEyNTBjZDg5YzgzNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.b3f8ne65O6j0AkrTaOcsrWYNYGvHNUZ8eVkrHWzl-ow)
> 
> What do you think? I did with a `btn btn-sm btn-outline-primary`

That looks more better, even I asked others. They too felt this intuitive rather than having it inside sidebar

2024-05-10 15:38 UTC, Era-cell commented
@jviotti I have moved the dropdown to breadcrumb, maybe this time its good..

2024-05-10 21:32 UTC, jviotti requested changes
I left a few comments, but shaping up, and it does work already

2024-05-10 21:32 UTC, jviotti commented on layouts/partials/sidebar.html
> +    {{$selected_dialect := index (split .RelPermalink "/") 1}}
@Era-cell This variable is completely unused. If so, please delete it

2024-05-10 21:32 UTC, jviotti commented on layouts/partials/sidebar.html
> -<aside id="sidebar" class="border-end position-relative d-none d-xl-block">
Why was the `id` removed?

2024-05-10 21:32 UTC, jviotti commented on layouts/_default/section.html
> +  <div id="test-100"  class="flex-xl-grow-1 mw-100">
We shouldn't be adding any "test" `id`s, even more if they will just go unused.

2024-05-10 21:32 UTC, jviotti commented on layouts/partials/breadcrumb.html
> +  <div id="dialect-dropdown" class="dropdown mt-1">
`id`s should be added very sparingly. I don't think you need it here.

2024-05-10 21:32 UTC, jviotti commented on assets/main.scss
> +  padding-right: 10px;
Please no ad-hoc CSS styles when Bootstrap has pre-defined class helpers. In this case, you can use the `pe-X` padding helpers directly on the HTML. Take a look at the documentation for how to set padding in Bootstrap

2024-05-10 21:32 UTC, jviotti commented on assets/main.scss
> +  // min-width: 265px;
You can delete this commented style.

2024-05-10 21:32 UTC, jviotti commented on assets/main.scss
> +  overflow-y: auto
What is the reasoning for these `overflow` changes? If they improve the sidebar (I'm no longer seeing a scrolling bar, which is cool!) then let's send it as a separate PR and merge that first?

2024-05-10 21:32 UTC, jviotti commented on layouts/partials/breadcrumb.html
> +    <button class="btn btn-outline-primary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
Can you do a small button with `btn-sm` here? The current looks too big IMO

2024-05-10 21:32 UTC, jviotti commented on layouts/partials/breadcrumb.html
> +          <li><a class="dropdown-item" href="{{ ref . .RelPermalink }}">{{ .Title }}</a></li>
Can you tweak the dropdown options to not display the current dialect? i.e. if you are on 2020-12 and you open the dropdown, you shouldn't see 2020-12. 

Because we don't have any other dialect right now, that means that the dropdown would be empty. What we can do is show a disabled dropdown entry that says "More dialects coming soon!" or something like that, like we originally had on the sidebar?

2024-05-11 07:42 UTC, Era-cell commented on layouts/partials/sidebar.html
> -<aside id="sidebar" class="border-end position-relative d-none d-xl-block">
😅 my bad, I badly need to review my PR before asking for review. I'll note it

2024-05-11 08:02 UTC, Era-cell commented on layouts/partials/breadcrumb.html
> +  <div id="dialect-dropdown" class="dropdown mt-1">
Okay.. I am now using bootstrap classes

2024-05-11 08:03 UTC, Era-cell commented on assets/main.scss
> +  overflow-y: auto
Yeah! I  wanted the sidebar bar to scrollabe. Lets do it another PR

2024-05-11 08:07 UTC, Era-cell commented on layouts/partials/breadcrumb.html
> +          <li><a class="dropdown-item" href="{{ ref . .RelPermalink }}">{{ .Title }}</a></li>
Okay.. what I have done is commented out the options, because however we will do it ASAP..

2024-05-11 08:23 UTC, Era-cell commented on layouts/partials/breadcrumb.html
> +    <button class="btn btn-outline-primary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
I did change the button to small, but what about the dropdown elements? The minimum text sizing we can give using bootstrap class I guess is "fs-6" which is same as the default size.

2024-05-13 16:03 UTC, jviotti commented on layouts/partials/breadcrumb.html
> +      <li><a class="dropdown-item fs-6">More dialects coming soon!</a></li>
Please make this a disabled item: https://getbootstrap.com/docs/5.3/components/dropdowns/#disabled

2024-05-13 16:03 UTC, jviotti commented on layouts/partials/breadcrumb.html
> +      <li><a class="dropdown-item fs-6">More dialects coming soon!</a></li>
Also now that I see it, this feels a bit long. Maybe just "More coming soon!"?

2024-05-13 16:05 UTC, jviotti commented on layouts/partials/breadcrumb.html
> +        {{end}}
There is a lot of space inconsistencies in this snippet. For example, here you say `{{end}}`, but below you say `{{ end }}`. Also above you say `{{$selected_dialect := .dialect}}` where it should have been `{{ $selected_dialect := .dialect }}`. Make sure style is consistent with the rest of the project

2024-05-13 16:06 UTC, jviotti commented on layouts/partials/breadcrumb.html
> +  <div class="dropdown mt-1 pe-3" >
There is a weird space here before `>`. Be mindful of those details!

2024-05-13 16:07 UTC, jviotti commented on layouts/partials/breadcrumb.html
> +  <div class="dropdown mt-1 pe-3" >
Also, the `mt-1` is ruining the vertical alignment. I think you should get rid of that class

2024-05-13 17:07 UTC, Era-cell commented on layouts/partials/breadcrumb.html
> +  <div class="dropdown mt-1 pe-3" >
I have removed it...

2024-05-14 01:35 UTC, jviotti commented on layouts/partials/breadcrumb.html
> +        {{ if ne $selected_dialect .Title }}
This doesn't look right. You are looping over all sections (which there are none?) and making them disabled, while still adding the option for "More coming soon!" below without making that disabled (which is the one that should have been disabled)

2024-05-14 01:36 UTC, jviotti commented on layouts/partials/breadcrumb.html
> +      <li><a class="dropdown-item"> More coming soon! </a></li>
Also, you added spaces before/after the square brackets, which is not the case elsewhere:

```suggestion
      <li><a class="dropdown-item">More coming soon!</a></li>
```

2024-05-14 07:41 UTC, Era-cell commented on layouts/partials/breadcrumb.html
> +        {{ if ne $selected_dialect .Title }}
Should I disable "More coming soon!" ? But right now we have only 2020-12. So, shouldn't that be enabled rn. I didn't understand the need of "More coming soon!" if its always disabled. If we enable all sections, right now the dropdown will display nothing.. which may make the user feel, why is the "Other dialect" button even existing.

2024-05-14 11:57 UTC, jviotti commented on layouts/partials/breadcrumb.html
> +        {{ if ne $selected_dialect .Title }}
> Should I disable "More coming soon!" ?

Correct. That doesn't make sense as clickable, as where would it redirect if so?

>  But right now we have only 2020-12. So, shouldn't that be enabled rn

No. Because we only support 2020-12, you are always within the 2020-12 context, so displaying 2020-12 in the dropdown again doesn't make sense. The dropdown should list the options that are NOT the current one. There is no point in making the user navigate to the same place they are already in!

> If we enable all sections, right now the dropdown will display nothing.. which may make the user feel, why is the "Other dialect" button even existing.

The dropdown wouldn't be empty. It'd display a single disabled element: "More coming soon!"

2024-05-14 15:18 UTC, Era-cell commented on layouts/partials/breadcrumb.html
> +        {{ if ne $selected_dialect .Title }}
> No. Because we only support 2020-12, you are always within the 2020-12 context, so displaying 2020-12 in the dropdown again doesn't make sense. The dropdown should list the options that are NOT the current one. There is no point in making the user navigate to the same place they are already in!

Oh shet! "that" I mean the loop. However I understood the importance of disabled item. I guess I have got it right this time

2024-05-14 15:21 UTC, Era-cell commented on layouts/partials/breadcrumb.html
> +      <li><a class="dropdown-item"> More coming soon! </a></li>
@jviotti I have made the changes.

2024-05-15 00:24 UTC, merged