Keyword `dynamicRef`
Intelligence-AI/learnjsonschema.com pull request #236
Opened 2024-05-20 19:29 UTC by AgniveshChaubey

This PR addresses #55.

2024-05-22 16:34 UTC, jviotti commented on content/2020-12/core/dynamicRef.markdown
> +Additionally, a JSON Schema reference URI may contain a JSON Pointer. For this
This paragraph is not applicable to anchors

2024-05-22 16:36 UTC, jviotti commented on content/2020-12/core/dynamicRef.markdown
> +    "$defs": {
Also as I said on the other PR, this `$defs` is invalid and the `$id` is unused

2024-05-22 16:37 UTC, jviotti commented on content/2020-12/core/dynamicRef.markdown
> +  "$id": "https://example.com/2",
`$id` is unused here too. Let's not put `$id` if examples don't rely on it, like for other keywords you documented

2024-05-22 16:38 UTC, jviotti commented on content/2020-12/core/dynamicRef.markdown
> +  "$id": "https://example.com/2",
Let's use a more semantic identifier here rather than just "2". Maybe "top-level" or "root"?

2024-05-22 16:39 UTC, jviotti commented on content/2020-12/core/dynamicRef.markdown
> +    "foo": {
I'm not sure I follow this example. There is a `foo` that is completely unused and a dynamic ref to an anchor that would only resolve to one place (as this anchor it outside the other schema resource)

2024-05-22 16:40 UTC, jviotti commented on content/2020-12/core/dynamicRef.markdown
> +      "$anchor": "items",
This example doesn't really show anything, as this anchor applies to the identifier of the root schema resource and wouldn't be visible to the embedded schema resource anyway

2024-05-22 16:40 UTC, jviotti commented on content/2020-12/core/dynamicRef.markdown
> +{{<learning-more>}}
Let's put this alert when describing the keyword. Otherwise nobody will find it down here

2024-05-22 16:45 UTC, jviotti requested changes
There are various important parts of dynamic references that are not being explained here. I'd expect:

- A mention of the "bookending" requirement and what that means
- A dynamic reference that contains more than just a fragment (i.e. `$dynamicRef: "foo#bar"`) and how that is resolved (non-fragment is always statically resolved and the fragment is maybe dynamically resolved)
- At least a mention to scopes in the description. i.e. that `$dynamicRef` will attempt to resolve the given fragment based on the dynamic scope at that given point in time

I think this is the best example from the test case that you can adapt and discuss: https://github.com/json-schema-org/JSON-Schema-Test-Suite/blob/main/tests/draft2020-12/dynamicRef.json#L477-L513. It shows many of the above things already in a single example

2024-05-22 16:46 UTC, jviotti commented on content/2020-12/core/dynamicRef.markdown
> +{{<schema `Schema with '$dynamicAnchor' and '$dynamicRef' keyword`>}}
I'd replace this example with an adaptation of the `if`/`then`/`else` example I suggested in the other comment, and put it as the first example in the page.

2024-05-22 16:46 UTC, jviotti commented
I think you could mention the bookending requirement as a "common pitfall" alert. Most people miss that

2024-05-22 16:47 UTC, jviotti commented on content/2020-12/core/dynamicRef.markdown
> +The `$dynamicRef` keyword is a dynamic applicator that allows for runtime resolution of schema references. Unlike the static `$ref`, which resolves the referenced schema at schema load time, `$dynami
I think it'd also be fun to add one line to this description stating that official meta-schemas use this mechanism themselves for defining vocabularies!

2024-05-24 04:34 UTC, AgniveshChaubey commented on content/2020-12/core/dynamicRef.markdown
> +      "$anchor": "items",
This is what I wanted to demonstrate with this example, that only `$dynamicAnchor` will be recognized in the embedded schema, not the `$anchor` and the `$dynamicRef` will be resolved to the first `$dynmicAnchor` encountered when the schema is resolved.

2024-05-24 08:37 UTC, AgniveshChaubey commented
Updated

1. Let me know if the description for bookending makes sense.

2. Taking referece from your blog post, I have explained that if/else example in detail, so that one can get good enough understanding of fynamic scoping here itself. Let me know if should should be included here or not.

2024-05-26 20:18 UTC, jviotti commented on content/2020-12/core/dynamicRef.markdown
> +**Bookending:** The bookending requirement means that when you use a `$dynamicRef`, the JSON Schema processor needs to find a matching `$dynamicAnchor` within the same schema scope to resolve the ref
I think a better way to explain it is that it is expected that the target schema resource of a dynamic reference (in case it's different than the destination) defines that actual anchor.

2024-05-26 20:19 UTC, jviotti commented on content/2020-12/core/dynamicRef.markdown
> +The `$dynamicRef` keyword is a dynamic applicator that allows for runtime resolution of schema references. Unlike the static `$ref`, which resolves the referenced schema at schema load time, `$dynami
One important thing to explain here is that if dynamic ref is not just a fragment, then the URI _except_ the fragment is statically resolved, and then only the fragment is dynamically resolved

2024-05-26 20:22 UTC, jviotti commented on content/2020-12/core/dynamicRef.markdown
> +          "$comment": "This is only needed to satisfy the bookending requirement",
This example is specifically about multiple dynamic anchors, so this comment is a lie: it's not only about the bookending requirement, but an integral part of the example? I say you leave the comment out!

2024-05-27 13:57 UTC, AgniveshChaubey commented
Updated!

2024-05-28 08:50 UTC, jviotti approved these changes

2024-05-29 04:41 UTC, merged