Algolia
Intelligence-AI/learnjsonschema.com pull request #239
Opened 2024-05-23 19:15 UTC by Era-cell

I tried fuse search and it was successful, please check if this works,
IF yes next will be:
searchbar positioning
Implement same for vocabulary page and dialect page
Customize fuseOptions much better

2024-05-24 09:17 UTC, jviotti commented on layouts/_default/index.json
What is this file? We shouldn't be committing generated files in this project. You can get Hugo to generate a JSON file automatically from the site content

2024-05-24 09:18 UTC, jviotti commented on config/_default/config.toml
> +
Empty line?

2024-05-24 09:19 UTC, jviotti commented on assets/main.scss
> +.btn-outline-success {
You should never override Bootstrap classes. Bootstrap provides a way to override main colors through SCSS variables and also supports plenty of helpers to customize colors, border colors, etc of arbitrary elements.

2024-05-24 09:20 UTC, jviotti commented on assets/main.js
> +var fuseOptions = {
`var` is an old and no longer used JavaScript construct. You should use `const` or `let`

2024-05-24 09:22 UTC, jviotti commented on layouts/partials/navigation.html
> +      <button class="btn btn-outline-success" type="submit">Search</button>
Probably no need to have a submit button, as it is not a form you would be submitting anyway. Ideally we just have the search input and we search as the user types?

2024-05-24 09:22 UTC, jviotti commented on layouts/partials/navigation.html
> +    <div class="navbar-nav d-flex ">
```suggestion
    <div class="navbar-nav d-flex">
```

2024-05-24 09:23 UTC, jviotti requested changes
I left a few comments have various comments about the JavaScript part, but it doesn't seem to work for me at all. I don't see anything if I type on the search bar or submit, as if nothing happens at all. Does it work for you?

2024-05-24 10:23 UTC, Era-cell commented on layouts/_default/index.json
Yeah, I saw that auto generation didn't work for me so I copied the information manually. Let me try it again to auto-generate

2024-05-24 10:25 UTC, Era-cell commented on config/_default/config.toml
> +
So, .toml files shouldn't have empty lines in the end?? I and any config file?.. I'll change it,

2024-05-24 10:31 UTC, Era-cell commented on layouts/partials/navigation.html
> +      <button class="btn btn-outline-success" type="submit">Search</button>
" Search as the user inputs" means we will keep redirecting as user inputs or keep changing suggestions like in JSON Schema website as user inputs ?? 1 or 2?

2024-05-24 10:32 UTC, Era-cell commented
> I left a few comments have various comments about the JavaScript part, but it doesn't seem to work for me at all. I don't see anything if I type on the search bar or submit, as if nothing happens at all. Does it work for you?

This is the recording of the working : it redirects directly, ..

https://github.com/Intelligence-AI/learnjsonschema.com/assets/77973415/0a2770e9-b3bc-4b21-be66-d2db978f1e4d

2024-05-26 19:49 UTC, jviotti commented
I don't get the dropdown at all. What browser are you using? Maybe try other ones?

https://github.com/Intelligence-AI/learnjsonschema.com/assets/2192773/078c8a95-3f84-4b87-af38-12c08ab38f5c

2024-05-26 19:51 UTC, jviotti commented on layouts/partials/navigation.html
> +      <button class="btn btn-outline-success" type="submit">Search</button>
No redirection. Exactly like in the JSON Schema official website: we dynamically change the dropdown with the search results

2024-05-26 19:51 UTC, jviotti commented on config/_default/config.toml
> +
I don't think any file format as a requirement of an empty line at the end that I'm aware of

2024-05-26 20:36 UTC, Era-cell commented
> I don't get the dropdown at all. What browser are you using? Maybe try other ones?
> 
>  Untitled.mov

That dropdown isn't code defined, yeah its because of the browser - Chrome browser. 

> I don't get the dropdown at all. What browser are you using? Maybe try other ones?
> 
>  Untitled.mov

That dropdown is a browser behavior. Right now it works only if the search button is clicked. Let's implement listing functionality too..

2024-05-26 21:12 UTC, jviotti commented on layouts/partials/navigation.html
> +      <button class="btn btn-outline-success" type="submit">Search</button>
You should be able to doing with plain JavaScript + Bootstrap. i.e. load a Bootstrap dropdown upon search results. Or if you can create a JavaScript function that gives you the search results given a search term as an array I can help doing the UI

2024-05-27 19:29 UTC, Era-cell commented
@jviotti I have made the major changes, styling and html should be polished.
Currently(functionality):
1. I have made it such that it clears everything on clicking outside, maybe we can give top suggestions
2. listing out top 10 results.
Change suggestions on these?

2024-05-28 08:52 UTC, jviotti commented
Seems to be shaping up but still doesn't work for me. It cannot find the JSON index file

<img width="1512" alt="Screenshot 2024-05-28 at 9 51 40 AM" src="https://github.com/Intelligence-AI/learnjsonschema.com/assets/2192773/f97f5826-b163-4552-b63b-570bc8552bde">

Also, can you resolve the git conflicts?

2024-06-03 14:33 UTC, jviotti commented
Woah! Super cool already! One small UI suggestion: when displaying a keyword, can you also showcase what dialect and vocabulary they belong to?

2024-06-03 14:34 UTC, jviotti commented
Can you extract the parts of this PR that generate the JSON index as a separate PR? I think we can get that merged now while we focus on polishing the rest

2024-06-03 14:34 UTC, jviotti commented on layouts/_default/baseof.html
> +    <script src="https://cdnjs.cloudflare.com/ajax/libs/fuse.js/6.6.2/fuse.min.js" integrity="sha512-Nqw1tH3mpavka9cQCc5zWWEZNfIPdOYyQFjlV1NvflEtQ0/XI6ZQ+H/D3YgJdqSUJlMLAPRj/oXlaHCFbFCjoQ==" crossori
Can we pull these dependencies using NPM on `package.json`?

2024-06-03 19:48 UTC, Era-cell commented
> Woah! Super cool already! One small UI suggestion: when displaying a keyword, can you also showcase what dialect and vocabulary they belong to?

Okay.. I got the reason for it . For the UI shall I include both of them in right as a smaller size text ? I may have to override bootstrap I guess

2024-06-03 20:49 UTC, jviotti commented
Not sure about the style. Give it your best shot while changing the least amount of possible in Bootstrap and then I'll help!

2024-06-04 16:20 UTC, Era-cell commented
@jviotti I have made the changes, I have updated package.json too, should I have another PR for index.json... 100%?

2024-06-04 20:12 UTC, jviotti commented
Yeah, let's do a separate PR. A sequence of smaller PRs is always better than 1 bigger PR! At least we have the JSON part out of the way, and we focus on the rest.

2024-07-01 10:09 UTC, closed without merging