add description and examples for `$id` keyword
Intelligence-AI/learnjsonschema.com pull request #45
Opened 2024-02-02 18:18 UTC by AgniveshChaubey

This is a follow-up PR addressing feedback from #33 and making suggested changes.

Not 100% sure how URN works. Tried with an example, but need some guidance here.

2024-02-02 18:21 UTC, AgniveshChaubey commented on content/2020-12/core/id.markdown
> +  "$id": "urn:example:vehicle",
I missed adding `$schema` here, I will add it later on

2024-02-02 19:04 UTC, AgniveshChaubey commented
I am not sure why the above check is still pending, even though the `website-build` workflow has been run successfully.
![image](https://github.com/Intelligence-AI/learnjsonschema.com/assets/113545196/22db7d80-99af-42d5-bf77-82d79c0437b5)

2024-02-03 00:09 UTC, jviotti requested changes
Taking really good shape! The URN example is correct

2024-02-03 00:09 UTC, jviotti commented on content/2020-12/core/id.markdown
> +The `$id` keyword declares an identifier for the schema and establishes the base URI for resolving other URI references within the schema. This keyword is resolved against the base URI of the overall
Now that I think about it, an interesting point we should clarify on a paragraph here is that if the identifier is a URL (i.e. an HTTP one), it is *common* for such URL to respond with the schema if i.e. resolved on a web browser, but that's not mandatory, as the URL is merely an identifier.

2024-02-03 00:09 UTC, jviotti commented on content/2020-12/core/id.markdown
> +  "$id": "https://example.com/schemas/address.json",
This says the schema is an address, but the example below is just "Hello World!" Maybe put a fake address in the example instead?

2024-02-03 00:09 UTC, jviotti commented on content/2020-12/core/id.markdown
> +- _The `$id` keyword declares the identifier `http://example.com/schemas/address.json` for the schema. This identifier can be used to reference the schema from other parts of the document or external
```suggestion
- _The `$id` keyword declares the URI `http://example.com/schemas/address.json` as the identifier for the schema. This URI serves as the base URI for resolving other URIs within the schema resource._
```

Or something like that?

2024-02-03 00:09 UTC, jviotti commented on content/2020-12/core/id.markdown
> +      "$id": "/address",
```suggestion
      "$id": "address",
```

Probably simpler?

2024-02-03 00:09 UTC, jviotti commented on content/2020-12/core/id.markdown
> +      "required": ["city", "postalCode"]
```suggestion
      "required": [ "city", "postalCode" ]
```

Spaces for consistency?

2024-02-03 00:09 UTC, jviotti commented on content/2020-12/core/id.markdown
> +      "$ref": "https://example.com/address"
```suggestion
      "$ref": "address"
```

Because the top level identifier is already based on `https://example.com`.

2024-02-03 00:09 UTC, jviotti commented on content/2020-12/core/id.markdown
> +{{<schema  `Schema with URN as value of $id`>}}
```suggestion
{{<schema `Schema with URN as value of $id`>}}
```

2024-02-03 00:09 UTC, jviotti commented on content/2020-12/core/id.markdown
> +{{</schema>}}
The example looks good. Maybe clarify that with URNs there is no such thing as a relative URN. i.e. you always have to fully type them down?

2024-02-03 00:09 UTC, jviotti commented on content/2020-12/core/id.markdown
> +{{</schema>}}
Also, can you add one example using Tag URIs (http://www.taguri.org), as JSON Schema is trying to promote them a bit? Maybe add a short paragraph explaining what they are? You can find examples on the referencing suite: https://github.com/python-jsonschema/referencing-suite/blob/main/tests/json-schema-draft-2020-12/tag-uris.json

2024-02-03 00:09 UTC, jviotti commented on content/2020-12/core/id.markdown
> +{{</schema>}}
The RFC is also a good read: http://www.faqs.org/rfcs/rfc4151.html

2024-02-03 00:10 UTC, jviotti commented
> I am not sure why the below check is still pending, even though the website-build workflow has been run successfully in my fork.

I think GitHub will not report it back until you are either a collaborator or have merged at least one PR. Let me actually make you a collaborator. Then you can also send PRs straight away without requiring a fork

2024-02-03 00:11 UTC, jviotti commented
Done!

<img width="800" alt="Screenshot 2024-02-02 at 20 11 38" src="https://github.com/Intelligence-AI/learnjsonschema.com/assets/2192773/d2162bbd-4956-4c89-9faf-8fa27d43f1dd">

2024-02-03 00:13 UTC, jviotti commented
I'm actually writing a blog post touching on schema resources and `$id`, so you might find these in-progress parts helpful:

<img width="986" alt="Screenshot 2024-02-02 at 20 12 45" src="https://github.com/Intelligence-AI/learnjsonschema.com/assets/2192773/412ddbba-469a-4a4b-9d13-1fde3cafc34f">
<img width="986" alt="Screenshot 2024-02-02 at 20 12 56" src="https://github.com/Intelligence-AI/learnjsonschema.com/assets/2192773/554f8b5a-3773-43a7-99bb-f0c63f8a4193">

2024-02-03 00:14 UTC, jviotti commented
`$id`, URIs, and schema resources are definitely confusing 😅 I think it will be great to have another JSON Schema contributor (you!) with a good grasp on them!

2024-02-03 00:15 UTC, jviotti commented on content/2020-12/core/id.markdown
> +The `$id` keyword declares an identifier for the schema and establishes the base URI for resolving other URI references within the schema. This keyword is resolved against the base URI of the overall
On the last point, we could also say that if you are not planning to make your URIs locatable (i.e. actually accessible over the protocol they declare, like HTTP), we advise to use URNs?

2024-02-03 00:16 UTC, jviotti commented on content/2020-12/core/id.markdown
> +{{</schema>}}
(Tag URIs are a *type* of URNs, so might be worth clarifying that)

2024-02-03 00:16 UTC, jviotti commented on content/2020-12/core/id.markdown
> +The `$id` keyword declares an identifier for the schema and establishes the base URI for resolving other URI references within the schema. This keyword is resolved against the base URI of the overall
Actually, given that URIs are so fundamental to all of this, maybe add a note suggesting the reader to go read the URI RFC to gain a deeper understanding on how resolution works?

2024-02-03 04:30 UTC, AgniveshChaubey commented on content/2020-12/core/id.markdown
> +      "$ref": "https://example.com/address"
I intentionally kept the absolute URI to explicitly indicate where the `$ref` is being resolved.

2024-02-03 11:19 UTC, AgniveshChaubey commented
Addressed all the requested changes.

Thanks for sharing your blog for the reference. However, the last section of your blog seems a bit confusing to me. I mean why _children schema resource_ is not considered as a part of _parent schema resource_? Is there any major difference between schema and schema resource?

Or is the above thing only applicable for the child schemas having the `$id` keyword?

2024-02-05 13:51 UTC, jviotti commented on content/2020-12/core/id.markdown
> +      "$ref": "https://example.com/address"
Alright!

2024-02-05 13:56 UTC, jviotti commented
> However, the last section of your blog seems a bit confusing to me. I mean why children schema resource is not considered as a part of parent schema resource? Is there any major difference between schema and schema resource?

Yeah, this is a common source of confusion that we should describe/exemplify well for this keyword. Essentially:

- A *schema* is the entire JSON boolean or JSON object you are passing to i.e. a validator
- A *schema* may consist of one or more *schema resources*. A schema resource is essentially an `$id` boundary. If you create nested schemas objects with `$id` in your schema, you are introducing new schema resources
- A *schema object* is a single subschema in the schema tree, only considering its immediate keywords and not considering nested subschemas

So the relationship is:

- A *schema* has one or more *schema resources*
- A *schema resource* has one or more *schema objects*
- A *schema object* has one or more *keywords*

Coming back to your original question, a schema resource does not include its children schema resources, as they are conceptually completely different entities, just that they are nested. That said, they are all part of the same *schema*

2024-02-06 03:54 UTC, closed without merging

2024-02-06 03:55 UTC, AgniveshChaubey commented
Changes addressed in #106

2024-02-06 04:00 UTC, AgniveshChaubey commented
Closing this PR as it is not passing the required checks. Requested changes are addressed in #106